global:
  scrape_interval: 1s

scrape_configs:

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    basic_auth:
      username: "symphony"
      password: "symphony"

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'prometheus:9090' ]